// <auto-generated />
using System;
using ISHRM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ISHRM.Migrations
{
    [DbContext(typeof(ClassProjectDBContext))]
    partial class ClassProjectDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30");

            modelBuilder.Entity("Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            CourseCode = "IS201",
                            CourseName = "Intro to IS Course"
                        },
                        new
                        {
                            CourseID = 2,
                            CourseCode = "IS303",
                            CourseName = "Javascript Programming"
                        },
                        new
                        {
                            CourseID = 3,
                            CourseCode = "IS110",
                            CourseName = "Excel Spreadsheets"
                        });
                });

            modelBuilder.Entity("ISHRM.Models.Alert", b =>
                {
                    b.Property<int>("AlertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartAlert")
                        .HasColumnType("TEXT");

                    b.HasKey("AlertID");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("ISHRM.Models.Position", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PositionID");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionID = 1,
                            PositionName = "RA"
                        },
                        new
                        {
                            PositionID = 2,
                            PositionName = "TA"
                        },
                        new
                        {
                            PositionID = 3,
                            PositionName = "Office"
                        },
                        new
                        {
                            PositionID = 4,
                            PositionName = "Student Instructor"
                        },
                        new
                        {
                            PositionID = 5,
                            PositionName = "Other"
                        });
                });

            modelBuilder.Entity("ISHRM.Models.ProgramYear", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProgramID");

                    b.ToTable("ProgramYears");

                    b.HasData(
                        new
                        {
                            ProgramID = 1,
                            ProgramName = "MSB Core"
                        },
                        new
                        {
                            ProgramID = 2,
                            ProgramName = "MISM"
                        },
                        new
                        {
                            ProgramID = 3,
                            ProgramName = "MBA"
                        },
                        new
                        {
                            ProgramID = 4,
                            ProgramName = "MPA"
                        },
                        new
                        {
                            ProgramID = 5,
                            ProgramName = "MACC"
                        },
                        new
                        {
                            ProgramID = 6,
                            ProgramName = "Other"
                        });
                });

            modelBuilder.Entity("ISHRM.Models.Student", b =>
                {
                    b.Property<int>("BYUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BYUName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<bool>("International")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NameChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NetID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("BYUID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ISHRM.Models.Student_Employment", b =>
                {
                    b.Property<int>("StudentEmploymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AuthorizationEmailSentDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuthorizationToWorkRec")
                        .HasColumnType("TEXT");

                    b.Property<int>("BYUID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmplRecord")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpectedHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPayInc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastPayIncAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PayGradTuition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PayIncDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("PayRate")
                        .HasColumnType("REAL");

                    b.Property<int>("PositionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgramID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgramYearProgramID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("QualtricsSent")
                        .HasColumnType("TEXT");

                    b.Property<int>("SemesterYearID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Semester_YearSemesterYearID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentBYUID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedEForm")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupervisorID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Terminated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TerminationStart")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentEmploymentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("PositionID");

                    b.HasIndex("ProgramYearProgramID");

                    b.HasIndex("Semester_YearSemesterYearID");

                    b.HasIndex("StudentBYUID");

                    b.HasIndex("SupervisorID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ISHRM.Models.Supervisor", b =>
                {
                    b.Property<int>("SupervisorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupervisorFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisorLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SupervisorID");

                    b.ToTable("Supervisors");

                    b.HasData(
                        new
                        {
                            SupervisorID = 1,
                            SupervisorFirstName = "Greg",
                            SupervisorLastName = "Anderson"
                        },
                        new
                        {
                            SupervisorID = 2,
                            SupervisorFirstName = "Gove",
                            SupervisorLastName = "Allen"
                        },
                        new
                        {
                            SupervisorID = 3,
                            SupervisorFirstName = "Jeff",
                            SupervisorLastName = "Jenkins"
                        },
                        new
                        {
                            SupervisorID = 4,
                            SupervisorFirstName = "Degan",
                            SupervisorLastName = "Kettles"
                        });
                });

            modelBuilder.Entity("Semester_Year", b =>
                {
                    b.Property<int>("SemesterYearID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SemesterName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("SemesterYearID");

                    b.ToTable("SemesterYears");

                    b.HasData(
                        new
                        {
                            SemesterYearID = 1,
                            SemesterName = "Fall",
                            Year = 2021
                        },
                        new
                        {
                            SemesterYearID = 2,
                            SemesterName = "Winter",
                            Year = 2022
                        },
                        new
                        {
                            SemesterYearID = 3,
                            SemesterName = "Spring",
                            Year = 2022
                        },
                        new
                        {
                            SemesterYearID = 4,
                            SemesterName = "Summer",
                            Year = 2022
                        },
                        new
                        {
                            SemesterYearID = 5,
                            SemesterName = "Fall",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("ISHRM.Models.Student_Employment", b =>
                {
                    b.HasOne("Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISHRM.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISHRM.Models.ProgramYear", "ProgramYear")
                        .WithMany()
                        .HasForeignKey("ProgramYearProgramID");

                    b.HasOne("Semester_Year", "Semester_Year")
                        .WithMany()
                        .HasForeignKey("Semester_YearSemesterYearID");

                    b.HasOne("ISHRM.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentBYUID");

                    b.HasOne("ISHRM.Models.Supervisor", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
